# -*- coding: utf-8 -*-
"""Testing_Model_Path_Colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GhBkpHGx4vhpCWBkFXd1h8c4ANZIEeSD
"""

from google.colab import drive
drive.mount("/content/drive")

!pip install 'git+https://github.com/facebookresearch/detectron2.git'

# Commented out IPython magic to ensure Python compatibility.
#preliminary packages
import os
import shutil
import sys
import random
import math
import re
import time
import json #for VIA image annotator
from PIL import Image

# progress bar for training time for the aesthetic
from time import sleep
from tqdm import tqdm
#------------------------

import numpy as np
import pandas as pd
import cv2
import skimage
from skimage import io

# Detectron2
import torch
import torchvision
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer, ColorMode
from detectron2.data import MetadataCatalog, DatasetCatalog
from detectron2.data.datasets import register_coco_instances
from detectron2.structures import BoxMode

# Matplotlib
import matplotlib
import matplotlib.pyplot as plt
import pickle


#plotting pictures
# %matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import cm
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIRECTORY = "/content/drive/MyDrive/instance_segmentation/Detectron2/"
IMAGE_CLASS = "project_static_images"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIRECTORY, "images", IMAGE_CLASS)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

# Printing to screen
from pprint import pprint

config = get_cfg()
config.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
config.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.9 # set threshold for this model
config.MODEL.WEIGHTS = "/content/drive/MyDrive/instance_segmentation/Detectron2/logs_6/model_final.pth"
config.MODEL.ROI_HEADS.NUM_CLASSES = 1
inference = DefaultPredictor(config)

clean_instance = MetadataCatalog.get("goat_train_clean").set(thing_classes=["goat"])

def infer(file_image):
    output = inference(file_image)
    visualizer = Visualizer(img[:, :, ::-1], metadata = clean_instance,
                            instance_mode=ColorMode.IMAGE_BW, scale=0.9)
    out = visualizer.draw_instance_predictions(output["instances"].to("cpu"))
    return (out.get_image()[:, :, ::-1])

from google.colab.patches import cv2_imshow
img = cv2.imread("/content/drive/MyDrive/instance_segmentation/Detection2/images/project_images/16205495733_6a2830b6f3_w.jpg")
cv2_imshow(infer(img))
